//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiloBilgileri
    {
        public int UçakID { get; set; }
        public string UçakModeli { get; set; }
        public Nullable<int> UçakAdedi { get; set; }
        public Nullable<int> YolcuKapasitesi { get; set; }
        public string GövdeUzunluğu { get; set; }
        public string YerdenYüksekliği { get; set; }
        public string KanatAçıklığı { get; set; }
        public string AzamiKalkışAğırlığı { get; set; }
        public string AzamiKargoKapasitesi { get; set; }
    }
}
