//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class havayoluEntities : DbContext
    {
        public havayoluEntities()
            : base("name=havayoluEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FiloBilgileri> FiloBilgileris { get; set; }
        public virtual DbSet<musteriler> musterilers { get; set; }
        public virtual DbSet<MusteriUcakSeyehatBilgileri> MusteriUcakSeyehatBilgileris { get; set; }
        public virtual DbSet<Personeller> Personellers { get; set; }
        public virtual DbSet<SeyehatBilgileri> SeyehatBilgileris { get; set; }
    }
}
