//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriUcakSeyehatBilgileri
    {
        public int ID { get; set; }
        public Nullable<int> MusteriID { get; set; }
        public Nullable<int> UcakID { get; set; }
        public Nullable<int> SeyahatID { get; set; }
        public Nullable<System.DateTime> GidişTarih { get; set; }
        public Nullable<System.DateTime> DönüşTarih { get; set; }
    }
}
