//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class musteriler
    {
        public int MüşteriID { get; set; }
        public string MüşteriAd { get; set; }
        public string MüşteriSoyad { get; set; }
        public Nullable<long> MüşteriTC { get; set; }
        public Nullable<long> MüşteriTel { get; set; }
        public string MüşteriAdres { get; set; }
        public string MüşteriMail { get; set; }
        public Nullable<int> PersonelID { get; set; }
    }
}
